# Generated by Django 2.1.3 on 2021-08-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('recipe_pic', models.ImageField(upload_to='pics')),
                ('short_description', models.TextField()),
                ('ingredients', models.TextField()),
                ('recipe_details', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('recipe_by', models.CharField(max_length=100)),
                ('video_link', models.TextField()),
                ('recipe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe_category', verbose_name='Recipe Category')),
            ],
        ),
    ]
