# Generated by Django 2.1.3 on 2021-08-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe_category',
            options={'verbose_name': 'Recipe Category', 'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe_Category', verbose_name='Recipe Category'),
        ),
    ]
