# Generated by Django 2.1.3 on 2021-08-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210806_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe_Category', verbose_name='Recipe Category'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(max_length=150),
        ),
    ]
