# Generated by Django 2.1.3 on 2021-08-13 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210806_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe_Category', verbose_name='Recipe Category'),
        ),
    ]
